Models/ErrorViewModel.cs
namespace WeddingPlanner.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Models/LoginUserModel.cs
#pragma warning disable CS8618

using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace WeddingPlanner.Models;

[NotMapped]
public class LoginUser
{
    [Required(ErrorMessage = "is required")]
    [EmailAddress]
    [Display(Name =  "LoginEmail")]
    public string LoginEmail { get; set; }


    [Required(ErrorMessage = "is required")]
    [MinLength(8, ErrorMessage = "must be at least 8 chars")]
    [DataType(DataType.Password)]
    [Display(Name = "LoginPassword")]
    public string LoginPassword { get; set; }
}

Models/RSVPModel.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace WeddingPlanner.Models;

public class RSVP
{
    public int RSVPID { get; set; }
    public int WeddingId { get; set; }
    public int UserId { get; set; }
}

Models/UserModel.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace WeddingPlanner.Models;

public class User 
{
    [Key]
    public int UserId { get; set; }


    [Required(ErrorMessage = "is required")]
    [MinLength(2, ErrorMessage = "must be at least two chars")]
    [Display(Name = "firstName")]
    public string firstName { get; set; }


    [Required(ErrorMessage = "is required")]
    [MinLength(2, ErrorMessage = "must be at least two chars")]
    [Display(Name = "lastName")]
    public string lastName { get; set; }


    [Required(ErrorMessage = "is required")]
    [EmailAddress(ErrorMessage = "must be a valid email")]
    [Display(Name = "email")]
    public string email { get; set; }


    [Required(ErrorMessage = "is required")]
    [MinLength(8, ErrorMessage = "must be at least 8 chars")]
    [DataType(DataType.Password)]
    [Display(Name = "password")]
    public string password { get; set; }


    [NotMapped]
    [DataType(DataType.Password)]
    [Compare("password", ErrorMessage = "doesn't match password")]
    [Display(Name = "confirmpass")]
    public string confirmpass { get; set; }
    public DateTime created_at { get; set; } = DateTime.Now;
    public DateTime updated_at { get; set; } = DateTime.Now;
}

Models/WeddingModel.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
namespace WeddingPlanner.Models;

public class Wedding
{
    [Required(ErrorMessage = "is required")]
    public int WeddingId { get; set; }


    [Required(ErrorMessage = "is required")]
    public string WedderOne { get; set; }


    [Required(ErrorMessage = "is required")]
    public string WedderTwo { get; set; }


    [Required(ErrorMessage = "is required")]
    [Future]
    public DateTime Date { get; set; }


    [Required(ErrorMessage = "is required")]
    [MinLength(8, ErrorMessage ="must be at least 8 characters")]
    public string Address { get; set; }
    public DateTime Created_At { get; set; } = DateTime.Now;
    public DateTime Updated_At { get; set; } = DateTime.Now;
    public int UserId { get; set; }
    public User? WeddingPlanner { get; set; }
    public List<RSVP> Guests { get; set; }
} 

public class Future : ValidationAttribute
{
    protected override ValidationResult? IsValid(object? value, ValidationContext validationContext)
    {
        if (value == null)
        {
            return ValidationResult.Success;
        }
        DateTime date = (DateTime)value;
        if (date <= DateTime.Now)
        {
            return new ValidationResult("must be a future date");
        }
        return ValidationResult.Success;
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WeddingPlanner.Models;
namespace WeddingPlanner.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }
    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using WeddingPlanner.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;
namespace WeddingPlanner.Controllers;

public class UserController : Controller
{
    private WeddingPlannerContext db;
    public UserController(WeddingPlannerContext context)
    {
        db = context;
    }
    private int? UUID
    {
        get
        {
            return HttpContext.Session.GetInt32("UUID");
        }
    }

    private bool loggedIn
    {
        get
        {
            return UUID != null;
        }
    }
    [HttpGet("/")]
    public IActionResult Index()
    {
        if(loggedIn)
        {
            return Success();
        }
        return View("Index");
    }


    [HttpPost("/register")]
    public IActionResult Register(User newUser)
    {
        if(ModelState.IsValid)
        {
            if(db.User.Any(user => user.email == newUser.email))
            {
                ModelState.AddModelError("email", "is taken");
            }
        }

        if(ModelState.IsValid == false)
        {
            return Index();
        }
        PasswordHasher<User> hashed = new PasswordHasher<User>();
        newUser.password = hashed.HashPassword(newUser, newUser.password);
        db.User.Add(newUser);
        db.SaveChanges();
        HttpContext.Session.SetInt32("UUID", newUser.UserId);
        return Success();
    }


    [HttpGet("/login")]
    public IActionResult Enter()
    {
        if(loggedIn)
        {
            return Success();
        }
        return View("Index");
    }


    [HttpPost("/loggingin")]
    public IActionResult Login(LoginUser loginUser)
    {
        if(ModelState.IsValid == false)
        {
            return Enter();
        }

        User? dbUser = db.User.FirstOrDefault(loggedUser => loggedUser.email == loginUser.LoginEmail);

        if(dbUser == null)
        {
            ModelState.AddModelError("LoginEmail", "not found");
            return Enter();
        }

        PasswordHasher<LoginUser> hashed = new PasswordHasher<LoginUser>();
        PasswordVerificationResult pwCompare = hashed.VerifyHashedPassword(loginUser, dbUser.password, loginUser.LoginPassword);

        if(pwCompare == 0)
        {
            ModelState.AddModelError("LoginPassword", "is not correct");
            return Enter();
        }

        HttpContext.Session.SetInt32("UUID", dbUser.UserId);
        return Success();
    }


    [HttpGet("/success")]
    public IActionResult Success()
    {
        if(!loggedIn)
        {
            return Enter();
        }
        return View("Success");
    }

    [HttpPost("/logout")]
    public IActionResult Logout()
    {
        HttpContext.Session.Clear();
        return Enter();
    }
}

Controllers/WeddingController.cs
using Microsoft.AspNetCore.Mvc;
using WeddingPlanner.Models;
using Microsoft.EntityFrameworkCore;
namespace WeddingPlanner.Controllers;

public class WeddingController : Controller
{
    private WeddingPlannerContext db;
    public WeddingController(WeddingPlannerContext context)
    {
        db = context;
    }
    private int? UUID
    {
        get
        {
            return HttpContext.Session.GetInt32("UUID");
        }
    }

    private bool loggedIn
    {
        get
        {
            return UUID != null;
        }
    }


    [HttpGet("/weddings")]
    public IActionResult Dashboard()
    {
        if(!loggedIn)
        {
            return View("Index");
        }
        
        List<Wedding> AllWeddings = db.Wedding.ToList();
        return View("Dashboard", AllWeddings);
    }


    [HttpGet("/weddings/new")]
    public IActionResult PlanWedding()
    {
        return View("PlanWedding");
    }


    [HttpPost("/weddings/create")]
        public IActionResult NewWedding(Wedding newWedding)
    {

        if(ModelState.IsValid == false)
        {
            return PlanWedding();
        }

        db.Wedding.Add(newWedding);
        db.SaveChanges();
        return View("Dashboard");
    }


    [HttpPost("/weddings/{weddingId}/add")]
    public IActionResult AddGuests(RSVP newRSVP, int weddingId)
    {
        if (ModelState.IsValid == false)
        {
            return RedirectToAction("All");
        }
        db.RSVP.Add(newRSVP);
        db.SaveChanges();
        return RedirectToAction("Dashboard", new {weddingId = weddingId});
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WeddingPlanner</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WeddingPlanner.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WeddingPlanner</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wedding" asp-action="Dashboard">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <form asp-controller="User" asp-action="Logout" method="POST">
                                <button class="btn btn-danger">log out</button>
                            </form>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - WeddingPlanner - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/User/Index.cshtml
<div class="container">
    <h1>Welcome</h1>
    <div class="row mt-5">
        <div class="col-md">
            <partial name="_Register"></partial>
        </div>

        <div class="col-md">
            <partial name="_Login"></partial>
        </div>
    </div>
</div>

Views/User/Success.cshtml
<div class="container">
    <h1 class="text-success">Success!~</h1>
</div>

<form asp-controller="User" asp-action="Logout" method="POST">
    <button>log out</button>
</form>

Views/User/_Login.cshtml
@model LoginUser

<h1>Login</h1>

<form asp-controller="User" asp-action="Login" method="POST">
    <div class="mb-3">
        <label asp-for="LoginEmail"></label>
        <span asp-validation-for="LoginEmail" class="text-danger font-weight-bold"></span>
        <input asp-for="LoginEmail" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="LoginPassword"></label>
        <span asp-validation-for="LoginPassword" class="text-danger font-weight-bold"></span>
        <input asp-for="LoginPassword" class="form-control">
    </div>
    <button>Submit</button>
</form>

Views/User/_Register.cshtml
@model User

<h1>Register</h1>

<form asp-controller="User" asp-action="Register" method="POST">
    <div class="mb-3">
        <label asp-for="firstName"></label>
        <span asp-validation-for="firstName" class="text-danger font-weight-bold"></span>
        <input asp-for="firstName" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="lastName"></label>
        <span asp-validation-for="lastName" class="text-danger font-weight-bold"></span>
        <input asp-for="lastName" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="email"></label>
        <span asp-validation-for="email" class="text-danger font-weight-bold"></span>
        <input asp-for="email" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="password"></label>
        <span asp-validation-for="password" class="text-danger font-weight-bold"></span>
        <input asp-for="password" class="form-control">
    </div>

    <div class="mb-3">
        <label asp-for="confirmpass"></label>
        <span asp-validation-for="confirmpass" class="text-danger font-weight-bold"></span>
        <input asp-for="confirmpass" class="form-control">
    </div>
    <button>Submit</button>
</form>

Views/Wedding/Dashboard.cshtml
@model List<Wedding>

<div class="container">
    <table>
        <tr>
        <th>Wedding</th>
        <th>Date</th>
        <th>Location</th>
        <th>Guests</th>
        <th>Action</th>
        </tr>
        @{
            foreach (Wedding Wedding in Model)
            {
                <tr>
                    <td><a asp-action="ViewWedding" asp-route-weddingId="@Wedding.WeddingId">@Wedding.WedderOne " & " @Wedding.WedderTwo "'s Wedding"</a></td>
                    <td>@Wedding.Date</td>
                    <td>@Wedding.Address</td>
                    <td> " " </td>
                    @if (Wedding.Guests == null)
                    {
                        <td>0 Guests</td>
                    }
                    else
                    {
                        <td>@Wedding.Guests.Count()</td>
                    }
                    <td>
                    @if (Wedding.UserId == Context.Session.GetInt32("UUID"))
                    {
                        <form asp-action="CancelWedding" asp-route-weddingID="@Wedding.WeddingId" method="POST">
                            <button class="btn btn-danger">Cancel Wedding</button>
                        </form>
                    }
                    
                    else
                    {
                        if (Wedding.Guests != null)
                        {
                        <form asp-action="AddGuests" asp-route-weddingId="@Wedding.WeddingId" method="POST">
                            <button class="btn btn-info">
                                @if (Wedding.Guests.Any(u => u.UserId == Context.Session.GetInt32("UUID")))
                                {
                                    <span>Rescind RSVP</span>
                                }
                                else
                                {
                                    <span>RSVP</span>
                                }
                            </button>
                        </form>
                        }
                    }
                    </td>
                </tr>
            }
        }
    </table>
    <a asp-action="PlanWedding" class="btn btn-primary">Plan New Wedding!</a>
</div>

Views/Wedding/PlanWedding.cshtml
@model Wedding

<h1>Plan Your Wedding</h1>
<div class="container">
    <div class="row">
        <div class="col">
            <form asp-action="NewWedding" asp-controller="Wedding" method="POST">
                <input type="hidden" asp-for="UserId" value=@Context.Session.GetInt32("UUID")>
                <label asp-for="WedderOne"></label>
                <input asp-for="WedderOne">
                <label asp-for="WedderTwo"></label>
                <input asp-for="WedderTwo">
                <label asp-for="Date"></label>
                <input asp-for="Date">
                <label asp-for="Address"></label>
                <input asp-for="Address">
                <button>Create!</button>
            </form>
        </div>
    </div>
</div>